package IGU;

import Models.Clientes;
import Models.ClientesDAO;
import Models.Productos;
import Models.ProductosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class EmpleadoPizza extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmpleadoPizza.class.getName());

    /**
     * Creates new form EmpleadoPizza
     */
        double totalpagar = 0;
        ArrayList<String> listadetalles = new ArrayList<>();
    public EmpleadoPizza() {
        initComponents();
        setSize(1200, 650);
        setResizable(false);
        setTitle("Panel de Empleado");
        setLocationRelativeTo(null);
        this.repaint();
        cargarcombobox();
    }
    
    private void cargarcombobox(){
        ProductosDAO producto = new ProductosDAO();
        ComboBoxpizza.removeAllItems();
        List<String> pizzas = producto.filtarcategoria("pizza");
        for(String p : pizzas){
            ComboBoxpizza.addItem(p);
        
        }
        ComboBoxbebida.removeAllItems();
        List<String> bebidas = producto.filtarcategoria("bebida");
        for(String b : bebidas){
            ComboBoxbebida.addItem(b);
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxpizza = new javax.swing.JComboBox<>();
        ComboBoxtamanio = new javax.swing.JComboBox<>();
        Spinnerpizza = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        btnagregarpizza = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxbebida = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxtamaniob = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Spinnerbebida = new javax.swing.JSpinner();
        btnagregarbebida = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnorden = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 248, 225));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(230, 126, 34));

        btnsalir.setBackground(new java.awt.Color(255, 255, 255));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(0, 0, 0));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/salida.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Panel de Empleado");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Gemini_Generated_Image_he818khe818khe81-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 619, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pizza");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("tamaño");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Extras");

        ComboBoxpizza.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxpizza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxpizza.setForeground(new java.awt.Color(0, 0, 0));

        ComboBoxtamanio.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxtamanio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxtamanio.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxtamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequenia", "Mediana", "Grande" }));

        Spinnerpizza.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Queso");

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("Pepperoni");

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setText("Hongos");

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setText("Tocino");

        btnagregarpizza.setBackground(new java.awt.Color(39, 174, 96));
        btnagregarpizza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnagregarpizza.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarpizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mas.png"))); // NOI18N
        btnagregarpizza.setText("Agregar");
        btnagregarpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarpizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Spinnerpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox4))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(ComboBoxtamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnagregarpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(140, 140, 140))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxtamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel3)
                    .addComponent(Spinnerpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnagregarpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 600, 390));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bebidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Bebida");

        ComboBoxbebida.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxbebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxbebida.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tamaño");

        ComboBoxtamaniob.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxtamaniob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxtamaniob.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxtamaniob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequenia", "Mediano", "Grande" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad");

        Spinnerbebida.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        btnagregarbebida.setBackground(new java.awt.Color(39, 174, 96));
        btnagregarbebida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregarbebida.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarbebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mas.png"))); // NOI18N
        btnagregarbebida.setText("Agregar");
        btnagregarbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarbebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ComboBoxbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxtamaniob, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Spinnerbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnagregarbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBoxbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ComboBoxtamaniob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Spinnerbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnagregarbebida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 540, 230));

        txtbuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtbuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 430, -1));

        btnbuscar.setBackground(new java.awt.Color(39, 174, 96));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 120, 40));

        btnnuevo.setBackground(new java.awt.Color(39, 174, 96));
        btnnuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mas.png"))); // NOI18N
        btnnuevo.setText("Agregar");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 120, 40));

        btnorden.setBackground(new java.awt.Color(216, 67, 21));
        btnorden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnorden.setForeground(new java.awt.Color(255, 255, 255));
        btnorden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mas.png"))); // NOI18N
        btnorden.setText("Añadir Orden");
        btnorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenActionPerformed(evt);
            }
        });
        jPanel1.add(btnorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 250, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cedula:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtcedula.setEditable(false);
        txtcedula.setBackground(new java.awt.Color(255, 255, 255));
        txtcedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcedula.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        txtnombre.setEditable(false);
        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarbebidaActionPerformed
       String nombre = ComboBoxbebida.getSelectedItem().toString();
       String tamanio = ComboBoxtamaniob.getSelectedItem().toString();
       int cantidad = (int) Spinnerbebida.getValue();
       
       if(cantidad > 0){
           ProductosDAO producto = new ProductosDAO();
           double precio = producto.obtenerPrecio(nombre, tamanio);
           
           if(precio > 0){
               double subtotal = precio*cantidad;
               totalpagar += subtotal;
               listadetalles.add(cantidad + "  "+ nombre +"  "+ tamanio+"  $-"+subtotal);
               JOptionPane.showMessageDialog(null, "bebida agregada. Total acumulado $-"+totalpagar);
           
           }
           else {
               JOptionPane.showMessageDialog(null, "error al obtener el precio");
           }
       
       }
    }//GEN-LAST:event_btnagregarbebidaActionPerformed

    private void btnagregarpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarpizzaActionPerformed
        String nombre = ComboBoxpizza.getSelectedItem().toString();
        String tamanio = ComboBoxtamanio.getSelectedItem().toString();
        int cantidad = (int) Spinnerpizza.getValue();
        
        if(cantidad > 0){
            ProductosDAO producto = new ProductosDAO();
            double precio = producto.obtenerPrecio(nombre, tamanio);
            
            if(precio > 0){
                double subtotal = precio*cantidad;
                totalpagar += subtotal;
                listadetalles.add(cantidad + "  "+ nombre +"  "+ tamanio+"  $-"+subtotal );
                JOptionPane.showMessageDialog(null, "Pizza agregada. Total acumulado $-"+totalpagar);
            
            }
            else{
                JOptionPane.showMessageDialog(null, "Precio no encontrado");
            
            }
        }
    }//GEN-LAST:event_btnagregarpizzaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        if (evt.getSource() == btnsalir) {
            dispose();
            LoginInicio login = new LoginInicio();
            login.setVisible(true);

        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String cedula = txtbuscar.getText();

        if (!"".equals(cedula)) {
            ClientesDAO dao = new ClientesDAO();
            Clientes cliente = dao.buscarcedula(cedula);

            if (cliente != null) {
                txtcedula.setText(cliente.getCedula());
                txtnombre.setText(cliente.getNombre() + "   " + cliente.getApellido());

            } else {
                int respuesta = javax.swing.JOptionPane.showConfirmDialog(null,
                        "El cliente no existe. ¿Desea registrarlo?", "Cliente no encontrado",
                        javax.swing.JOptionPane.YES_NO_OPTION);
                
                if(respuesta == javax.swing.JOptionPane.YES_OPTION){
                    NuevoUser nuevo = new NuevoUser();
                    nuevo.setVisible(true);
                }
            }
        
        }
            else{
                    JOptionPane.showMessageDialog(null, "Ingrese una cedula para buscar");
                    
         }

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
       NuevoUser clienteN = new NuevoUser();
       clienteN.setVisible(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenActionPerformed
       if(totalpagar > 0 && !txtnombre.getText().isEmpty()){
           String nombreC = txtnombre.getText();
           Pago_Orden orden =new  Pago_Orden(totalpagar,nombreC,listadetalles);
           orden.setVisible(true);
       
       }
       else{
           JOptionPane.showMessageDialog(null, "debe seleccionar un cliente y agregar productos");
       }
    }//GEN-LAST:event_btnordenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmpleadoPizza().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxbebida;
    public javax.swing.JComboBox<String> ComboBoxpizza;
    public javax.swing.JComboBox<String> ComboBoxtamanio;
    public javax.swing.JComboBox<String> ComboBoxtamaniob;
    public javax.swing.JSpinner Spinnerbebida;
    public javax.swing.JSpinner Spinnerpizza;
    public javax.swing.JButton btnagregarbebida;
    public javax.swing.JButton btnagregarpizza;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JButton btnorden;
    private javax.swing.JButton btnsalir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtcedula;
    public javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
