/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import Models.Clientes;
import Models.ClientesDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class NuevoUser extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(NuevoUser.class.getName());

        /**
         * Creates new form NuevoUser
         */

        public NuevoUser() {
                initComponents();
                setSize(360, 536);
                setResizable(false);
                setTitle("Nuevo Usuario");
                setLocationRelativeTo(null);
                this.repaint();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jToggleButton1 = new javax.swing.JToggleButton();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtcedula = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtnombre = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtapellido = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txttelefono = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtdireccion = new javax.swing.JTextField();
                btn_salir = new javax.swing.JButton();
                btnanadir = new javax.swing.JButton();

                jToggleButton1.setText("jToggleButton1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setBackground(new java.awt.Color(255, 248, 225));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(93, 64, 55));
                jLabel1.setText("Nuevo Cliente");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(93, 64, 55));
                jLabel2.setText("Cedula:");

                txtcedula.setBackground(new java.awt.Color(255, 255, 255));
                txtcedula.setForeground(new java.awt.Color(0, 0, 0));

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(93, 64, 55));
                jLabel3.setText("Nombre:");

                txtnombre.setBackground(new java.awt.Color(255, 255, 255));
                txtnombre.setForeground(new java.awt.Color(0, 0, 0));

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(93, 64, 55));
                jLabel4.setText("Apellido:");

                txtapellido.setBackground(new java.awt.Color(255, 255, 255));
                txtapellido.setForeground(new java.awt.Color(0, 0, 0));

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(93, 64, 55));
                jLabel5.setText("Numero de Telefono:");

                txttelefono.setBackground(new java.awt.Color(255, 255, 255));
                txttelefono.setForeground(new java.awt.Color(0, 0, 0));

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(93, 64, 55));
                jLabel6.setText("Direccion:");

                txtdireccion.setBackground(new java.awt.Color(255, 255, 255));
                txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
                txtdireccion.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtdireccionActionPerformed(evt);
                        }
                });

                btn_salir.setBackground(new java.awt.Color(216, 67, 21));
                btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btn_salir.setForeground(new java.awt.Color(255, 255, 255));
                btn_salir.setText("Cancelar");
                btn_salir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_salirActionPerformed(evt);
                        }
                });

                btnanadir.setBackground(new java.awt.Color(216, 67, 21));
                btnanadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnanadir.setForeground(new java.awt.Color(255, 255, 255));
                btnanadir.setText("Añadir");
                btnanadir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnanadirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(29, 29, 29)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(txtnombre,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                290,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(txtapellido,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                290,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addComponent(txttelefono,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                290,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(txtcedula,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                290,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                .addComponent(btnanadir,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                125,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(btn_salir,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                125,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addComponent(txtdireccion,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                290,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(108, 108, 108)
                                                                                                .addComponent(jLabel1)))
                                                                .addContainerGap(41, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtcedula,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txtnombre,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txtapellido,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txttelefono,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txtdireccion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                28,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnanadir,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                44,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btn_salir,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                44,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(53, Short.MAX_VALUE)));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtdireccionActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtdireccionActionPerformed

        private void btnanadirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnanadirActionPerformed
                if (!txtcedula.getText().isEmpty() && !txtnombre.getText().isEmpty()) {
                        Clientes cliente = new Clientes();
                        cliente.setCedula(txtcedula.getText());
                        cliente.setNombre(txtnombre.getText());
                        cliente.setApellido(txtapellido.getText());
                        cliente.setTelefono(txttelefono.getText());
                        cliente.setDireccion(txtdireccion.getText());

                        ClientesDAO dao = new ClientesDAO();

                        if (txtcedula.getText().length() < 7 || txtcedula.getText().length() > 9) {
                                JOptionPane.showMessageDialog(null, "La cédula debe tener entre 7 y 9 dígitos");
                        } else if (dao.existeCedula(txtcedula.getText())) {
                                JOptionPane.showMessageDialog(null, "La cedula ya esta en uso");
                        } else if (dao.registrarcliente(cliente)) {
                                JOptionPane.showMessageDialog(null, "Cliente registrado exitosamente");
                                this.dispose();
                        } else {
                                JOptionPane.showMessageDialog(null, "Debe llenar los campos");
                        }

                }
        }// GEN-LAST:event_btnanadirActionPerformed

        private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_salirActionPerformed
                this.dispose();
        }// GEN-LAST:event_btn_salirActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new NuevoUser().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton btn_salir;
        public javax.swing.JButton btnanadir;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JToggleButton jToggleButton1;
        public javax.swing.JTextField txtapellido;
        public javax.swing.JTextField txtcedula;
        public javax.swing.JTextField txtdireccion;
        public javax.swing.JTextField txtnombre;
        public javax.swing.JTextField txttelefono;
        // End of variables declaration//GEN-END:variables
}
