/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import Models.VentasDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Models.Clientes;
import Models.ClientesDAO;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author admin
 */
public class Pago_Orden extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pago_Orden.class.getName());

    /**
     * Creates new form Pago_Orden
     */
    private double montototal;
    private String nombrecliente;
    private List<String> detalles;

    private ArrayList<Models.Ventas> listaProductos;
    private int idCliente;
    private int idEmpleado;
    private EmpleadoPizza empleadoPizza;
    private double iva;

    public Pago_Orden() {
        initComponents();

    }

    public Pago_Orden(double montototal, String cliente, List<String> items, ArrayList<Models.Ventas> productos, int idCli, int idEmp,
            EmpleadoPizza parent) {
        initComponents();
        setResizable(false);
        setTitle("Pago de la orden");
        setLocationRelativeTo(null);
        this.repaint();
        this.montototal = montototal;
        this.nombrecliente = cliente;
        this.detalles = items;
        this.listaProductos = productos;
        this.idCliente = idCli;
        this.idEmpleado = idEmp;
        this.empleadoPizza = parent;

        txtsubtotal.setText("Bs" + this.montototal);
        double mon = montototal;
        double ivita = mon* 0.06;
        txtiva.setText("Bs" + String.format("%.2f", ivita));
        txttotal.setText("Bs" + String.format("%.2f", (mon + ivita)));

        cargarticket();

    }

    private void cargarticket() {

        ticket.setText("");
        ticket.append("\n");

        for (String items : detalles) {
            ticket.append(items + "\n");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_pagar = new javax.swing.JButton();
        txtiva = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        btn_cancelarP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticket = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 248, 225));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resumen de la orden");

        jPanel5.setBackground(new java.awt.Color(243, 229, 171));
        jPanel5.setForeground(new java.awt.Color(243, 229, 171));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("SubTotal");

        txtsubtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsubtotal.setForeground(new java.awt.Color(0, 0, 0));
        txtsubtotal.setText("$55");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("IVA(6%)");

        btn_pagar.setBackground(new java.awt.Color(216, 67, 21));
        btn_pagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_pagar.setForeground(new java.awt.Color(255, 255, 255));
        btn_pagar.setText("Pagar");
        btn_pagar.setPreferredSize(new java.awt.Dimension(50, 30));
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });

        txtiva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtiva.setForeground(new java.awt.Color(0, 0, 0));
        txtiva.setText("$4");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Total");

        txttotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttotal.setForeground(new java.awt.Color(216, 67, 21));
        txttotal.setText("$59");

        btn_cancelarP.setBackground(new java.awt.Color(216, 67, 21));
        btn_cancelarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cancelarP.setText("Cancelar");
        btn_cancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_cancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btn_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtiva)
                            .addComponent(txtsubtotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal)))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtsubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtiva))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        ticket.setEditable(false);
        ticket.setBackground(new java.awt.Color(255, 255, 255));
        ticket.setColumns(20);
        ticket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ticket.setForeground(new java.awt.Color(0, 0, 0));
        ticket.setRows(5);
        jScrollPane1.setViewportView(ticket);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 585));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarPActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarPActionPerformed

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        VentasDAO ventasDAO = new VentasDAO();
        ClientesDAO clientesDAO = new ClientesDAO();
        

        int id_venta = ventasDAO.registrarventa(idCliente, idEmpleado);

        if (id_venta > 0) {
            boolean error = false;
            boolean detalles = true;

            for (Models.Ventas v : listaProductos) {
                double total = v.getPreciounitario() * v.getCantidad();
                double total2 = total * 1.06;
               

                boolean registrado = ventasDAO.registrardetallefactura(id_venta, v.getCodigo(), v.getCantidad(), total2);

                if (!registrado) {
                    error = true;
                    detalles = false;
                }

            }
            
                if(detalles){
                Clientes datosCliente = clientesDAO.obtenerCliente(idCliente);
                String nombreCompleto = (datosCliente != null) ? datosCliente.getNombre() + " " + datosCliente.getApellido() : nombrecliente;
                String cedulaCliente = (datosCliente != null) ? datosCliente.getCedula() : "N/A";
                double totalfinal2 = montototal * 0.06;
                 double totalFinal = montototal+ totalfinal2;
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                String fechaActual = sdf.format(new Date());
                
                StringBuilder factura = new StringBuilder();
                factura.append("================================\n");
                factura.append("         GUAROS PIZZAS          \n");
                factura.append("================================\n");
                factura.append("Fecha:   ").append(fechaActual).append("\n");
                factura.append("Cliente: ").append(nombreCompleto).append("\n");
                factura.append("Cédula:  ").append(cedulaCliente).append("\n");
                factura.append("--------------------------------\n");
                factura.append("PRODUCTOS COMPRADOS:\n");
                
                for (Models.Ventas prod : listaProductos) {
                    factura.append("- ").append(prod.getNombre())
                           .append(" (x").append(prod.getCantidad()).append(")\n");
                }
                
                factura.append("--------------------------------\n");
                factura.append("Subtotal:  ").append(txtsubtotal.getText()).append(" Bs\n"); 
                factura.append("IVA (6%): ").append(txtiva.getText()).append(" Bs\n");
                factura.append("TOTAL:     ").append(String.format("%.2f", totalFinal)).append("Bs\n");
                factura.append("================================\n");
                factura.append("    ¡Gracias por su compra!     \n");
                
                JOptionPane.showMessageDialog(this, factura.toString(), "Factura de Compra", JOptionPane.INFORMATION_MESSAGE);
                
                   if (!error) {

                empleadoPizza.limpiarTodo();
                this.dispose();

            } 
            
            }else {
                JOptionPane.showMessageDialog(this, "Error al guardar algunos detalles de la factura.");

            }
            
        

        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la venta en base de datos.");

        }
    }//GEN-LAST:event_btn_pagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pago_Orden().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancelarP;
    public javax.swing.JButton btn_pagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ticket;
    public javax.swing.JLabel txtiva;
    public javax.swing.JLabel txtsubtotal;
    public javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
